ecommerseproject/ecommerseproject/cart/urls.py
from . import views
from django.urls import path, include
app_name='cart'

urlpatterns = [
    path('add/<int:product_id>', views.add_cart,name='add_cart'),
    path('', views.cart_detail,name='cart_detail'),
    path('remove_cart/<int:product_id>',views.remove_cart,name='remove_cart'),
    path('full_remove/<int:product_id>',views.full_remove,name='full_remove'),

]

ecommerseproject/ecommerseproject/ecommerseapp/urls.py
from . import views
from django.urls import path, include
app_name='shop'

urlpatterns = [

    path('', views.allproductcat,name='allproductcat'),
    path('<slug:c_slug>/',views.allproductcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>',views.prodetail,name='proDetail')
]

ecommerseproject/ecommerseproject/ecommerseproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerseapp/', include('ecommerseapp.urls')),
    path('searchapp/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerseproject/ecommerseproject/searchapp/urls.py
from . import views
from django.urls import path, include
app_name='searchapp'

urlpatterns = [

    path('', views.SearchResult,name='SearchResult'),

]

ecommerseproject/ecommerseproject/cart/models.py
from django.db import models
from ecommerseapp.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerseproject/ecommerseproject/ecommerseapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('shop:proDetail',args=[self.category.slug,self.slug])

ecommerseproject/ecommerseproject/searchapp/models.py
from django.db import models

# Create your models here.

ecommerseproject/ecommerseproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerseapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity+=1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price*cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total))


def remove_cart(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerseproject/ecommerseproject/ecommerseapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.
def allproductcat(request,c_slug=None):
    c_page=None
    Products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        Products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        Products_list=Product.objects.all().filter(available=True)

    paginator=Paginator(Products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        Products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        Products=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'products':Products})


def prodetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerseproject/ecommerseproject/searchapp/views.py
from django.shortcuts import render
from ecommerseapp.models import Product
from django.db.models import Q

# Create your views here.
def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerseproject/ecommerseproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" >
    <script src="https://kit.fontawesome.com/eb9946367f.js" crossorigin="anonymous"></script>
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription%} {%endblock%}">
    <title>{%block title%}{%endblock%}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}
</div>
{% include 'footer.html' %}
<script type="text/javascript" src="{% static 'js/slim.min.js' %}" ></script>
 <script type="text/javascript" src="{% static 'js/popper.min.js' %}" ></script>


<script type="text/javascript" src="{% static 'js/boostrap.min.js' %}" ></script>
</body>
</html>

ecommerseproject/ecommerseproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

  This is cart page.Proceed to review your items and place the order

{% endblock %}
{% block title %}
Cart
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart is Empty</h1>
        <br>
        <p class="text-center">Please click <a href="{% url 'shop:allproductcat'%}">here</a></p>to continue shopping.
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
            <br>
        </h1>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" width="100px"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}<br>
                   SKU: {{cart_item.product.id}}<br>
                    Price: {{cart_item.product.price}} <br>
                    Quantity:{{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>

                    $ {{ cart_item.sub_total }}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:remove_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>&nbsp;
                </td>
                {% else %}
                <td>

                    <a href="{% url 'cart:remove_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>&nbsp;
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

     <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>Check Out</th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your total is: <strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
         <div class="mx-auto" style="padding-bottom:10px">
            <a href="{% url 'shop:allproductcat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
         </div>
     </div>
</div>
{% endif %}
{% endblock %}

ecommerseproject/ecommerseproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:150}}
    {% else %}
        Welcome to EasyShop
    {% endif %}
{% endblock %}


{% block title %}
    {% if category %}
        {{category.name}}-EasyShop
    {% else %}
        see our new collection
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
                <p class="text-center"><a href="{% url 'shop:allproductcat'%}">Our product collection</a></p>
            </div>
        </div>
    </div>
{%endif%}

<div class="mx_auto">
    {% if category %}
        <img  class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
        </div>
         <br>
        <div>
            <h1 class="text-center my_title">{{category.name}}</h1>
            <p class="text-justify">{{category.description}}</p>
        </div>
    {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="banner" height="150px" width="100%">
        </div>
    <br>
    <div>

        <h1>Our Product Collections</h1>
        <p>It is a long established fact that a reader will be distracted by the
            readable content of a page when looking at its layout. The point of using Lorem
            Ipsum is that it has a more-or-less normal distribution of letters, as opposed to
            using 'Content here, content here', making it look like readable English. Many desktop
            publishing packages and web page editors now use Lorem Ipsum as their default model text,
            and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various
            versions have evolved over the years, sometimes by accident, sometimes on purpose
            (injected humour and the like).</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="row mx_auto">
            {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
                <div class="card text-center" style="min-width:18rem;">
                    <div>
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                </div>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
                </div>
                    </div>
            {% endfor %}
        </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}
            <hr>
            <div class="text-center">
              {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

ecommerseproject/ecommerseproject/templates/footer.html
<div class="footer navbar-fixed-bottom
my_footer">
    <p class="text-center">ABC tech pvt ltd.</p>
</div>

ecommerseproject/ecommerseproject/templates/header.html
{% load static %}
<header>
  <center><a href="{% url 'shop:allproductcat' %}"><img src="{% static 'img/logo.png' %}" alt="log image" width="100px"></a></center>
</header>

ecommerseproject/ecommerseproject/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ecommerseproject/ecommerseproject/templates/navbar.html
 <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'shop:allproductcat' %}">All</a>
            {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
        </div>
        </li>
          {% if item_count > 0 %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
          {% endif %}
      </ul>
        </div>
     <div>
        <form class="form-inline my-2 my-lg-0" action="{% url 'searchapp:SearchResult' %}">
     <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
     <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
    </div>
  </nav>

ecommerseproject/ecommerseproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{category.description|truncatewords:150}}
{% endblock %}

{% block title %}
        {{product.name}}-EasyShop
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allproductcat'%}">Home</a>|
        <a href="{{product.category.get_url}}">{{product.category}}</a>{{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18 rem">
            <img class="my_image" src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>


    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
        <h1 class="my_prod_title">{{product.name}}</h1>
        <p>{{product.price}}</p>
        <p class="my_title"><u>product description</u></p>
        <p class="text-justify my_prod_text">{{product.description}}</p>
        {% if product.stock <= 0%}
        <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
        {% else %}
        <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
        {% endif %}
        </div>
    </div>
</div>
</div>

{% endblock %}

ecommerseproject/ecommerseproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        We have variety of products.

{% endblock %}
{% block title %}
search
{% endblock %}

{% block content %}
<div>
<p class="text-center my_search_title">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="row mx_auto">
            {% for product in products%}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
                <div class="card text-center" style="min-width:18rem;">
                    <div>
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                </div>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
                </div>
                    </div>
    {% empty %}
    <div class="mx_auto">
        <p class="text-center my_search_title">0 search results found</p>
    </div>
            {% endfor %}
        </div>
{% endblock %}